language: node_js
node_js:
- "6"
before_install:
- git config --global user.name "Sergey Chystiakov"
- git config --global user.email "anyxem@gmail.com"
- git config --global credential.helper "store --file=.git/credentials"
- echo "https://${GITHUB_API_KEY}:@github.com" > .git/credentials
script: gulp deploy
